//Non volatile config
//Changed settings will be written to / loaded from a file called nvconfig.cfg
//If a nonvolatile setting is changed it is saved to that file immediately

#define MAX_NVCONFIG_SIZE 2048*128

#define NV_ConfigInit NV_LoadConfig
#define NV_ProcessBegin NV_LoadConfig
#define NV_ProcessEnd NV_WriteConfig

/*
================
NV_ClearAdminList
================
*/
void NV_ClearAdminList(){

    adminPower_t *admin, **this;

    for ( this = &psvs.adminpower, admin = *this; admin ; admin = *this ){
        *this = admin->next;
        Z_Free(admin);
    }
}

/*
================
NV_ParseConfigLine
================
*/

qboolean NV_ParseConfigLine(char* line, int linenumber){

    adminPower_t *admin;
    int uid, power;
    const char* cmdname;
    char username[32];
    char password[65];
    char salt[129];
    char tmp[1024];

    if(!Q_stricmp(Info_ValueForKey(line, "type") , "cmdMinPower")){

        power = atoi(Info_ValueForKey(line, "power"));
        cmdname = Info_ValueForKey(line, "cmd");
        if(!Cmd_SetPower(cmdname, power)){
            Com_DPrintf("Warning: Commandname %s not known yet (line: %d)\n", cmdname, linenumber);
            return qtrue; //Don't rise errors here! This can happen for commands we add at a later stage
        }
        return qtrue;

    }else if(!Q_stricmp(Info_ValueForKey(line, "type") , "rconAdmin")){

        power = atoi(Info_ValueForKey(line, "power"));
        Q_strncpyz(password, Info_ValueForKey(line, "password") , sizeof(password));
        Q_strncpyz(salt, Info_ValueForKey(line, "salt") , sizeof(salt));
        Q_strncpyz(username, Info_ValueForKey(line, "username") , sizeof(username));

        if(!HL2Rcon_AddSourceRconAdminToList(username, password, salt, power)){
            Com_Printf("Error: duplicated username or bad power or too many admins (line: %d)\n", linenumber);
            return qfalse;
        }
        return qtrue;

    }else if(!Q_stricmp(Info_ValueForKey(line, "type") , "admin")){

        uid = atoi(Info_ValueForKey(line, "uid"));

        if(uid == 0)
            Q_strncpyz(tmp, Info_ValueForKey(line, "guid"), sizeof(tmp));

        power = atoi(Info_ValueForKey(line, "power"));

        if((uid < 1 && strlen(tmp) != 8)){
            Com_Printf("Error: Invalid uid / guid (line: %d)\n", linenumber);
            return qfalse;
        }
        if(power < 1){
            Com_Printf("Error: Invalid powerlevel(%i). Powerlevel can not be less than 1. (line: %d)\n", linenumber);
            return qfalse;
        }
        admin = Z_Malloc(sizeof(adminPower_t));
        if(admin){
            admin->uid = uid;
            admin->power = power;
            admin->next = psvs.adminpower;
            psvs.adminpower = admin;
            return qtrue;

        }else{
            return qfalse;
        }

    }else{
        Com_Printf("Error: unknown type (line: %d)\n", linenumber);
        return qfalse;
    }
}


/*
================
NV_LoadConfig
================
*/

void NV_LoadConfig(){

    int read, i;
    int error = 0;
    char buf[256];
    *buf = 0;
    fileHandle_t file;

    NV_ClearAdminList();
    HL2Rcon_ClearSourceRconAdminList();

    FS_SV_FOpenFileRead("nvconfig.dat", &file);
    if(!file){
        Com_DPrintf("Couldn't open nvconfig.dat for reading\n");
        return;
    }
    Com_Printf( "loading nvconfig.dat\n");
    loadconfigfiles = qtrue;

    i = 0;

    while(qtrue){
        read = FS_ReadLine(buf,sizeof(buf),file);
        if(read == 0){
            FS_FCloseFile(file);
            loadconfigfiles = qfalse;
            Com_Printf("Loaded nvconfig.dat %i errors\n", error);
            return;
        }
        if(read == -1){
            Com_Printf("Can not read from nvconfig.dat\n");
            FS_FCloseFile(file);
            loadconfigfiles = qfalse;
            return;
        }
        i++;//linecouter

        if(!*buf || *buf == '/' || *buf == '\n'){
            continue;
        }
        if(!NV_ParseConfigLine(buf, i)){
            error++;
        }
    }
}

/*
================
NV_WriteConfig
================
*/

void NV_WriteConfig(){

    char* buffer;
    char infostring[1024];
    int i;

    buffer = Hunk_AllocateTempMemory(MAX_NVCONFIG_SIZE);
    if(!buffer){
        Com_Printf( "Error Updating NVConfig: Hunk_Alloc failed\n" );
        return;
    }
    Com_Memset(buffer,0,MAX_NVCONFIG_SIZE);
    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"//Autogenerated non volatile config settings\n");

    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"\n//Minimum power settings\n");
    cmd_function_t *cmd;
    for ( cmd = cmd_functions ; cmd ; cmd = cmd->next ){
        *infostring = 0;
        Info_SetValueForKey(infostring, "type", "cmdMinPower");
        Info_SetValueForKey(infostring, "cmd", cmd->name);
        Info_SetValueForKey(infostring, "power", va("%i",cmd->minPower));
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, infostring);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, "\\\n");
    }

    adminPower_t *admin;
    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"\n//Admins | Users power settings\n");
    for ( admin = psvs.adminpower ; admin ; admin = admin->next ){
        *infostring = 0;
        Info_SetValueForKey(infostring, "type", "admin");

        if(admin->uid != 0)
            Info_SetValueForKey(infostring, "uid", va("%i",admin->uid));
        else
            Info_SetValueForKey(infostring, "guid", admin->guid);

        Info_SetValueForKey(infostring, "power", va("%i",admin->power));
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, infostring);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, "\\\n");
    }

    rconLogin_t *rconadmin;
    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"\n//RconAdmins\n");

    for ( rconadmin = sourceRcon.rconUsers, i = 0; i < MAX_RCONLOGINS ; rconadmin++, i++ ){
        *infostring = 0;
	if(!*rconadmin->username)
		continue;
        Info_SetValueForKey(infostring, "type", "rconAdmin");
        Info_SetValueForKey(infostring, "power", va("%i", rconadmin->power));
        Info_SetValueForKey(infostring, "password", rconadmin->sha256);
        Info_SetValueForKey(infostring, "salt", rconadmin->salt);
        Info_SetValueForKey(infostring, "username", rconadmin->username);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, infostring);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, "\\\n");
    }


    FS_SV_WriteFile("nvconfig.dat",buffer,strlen(buffer));
    Hunk_FreeTempMemory(buffer);
    Com_DPrintf("NV-Config Updated\n");
}
