//Non volatile config
//Changed settings will be written to / loaded from a file called nvconfig.cfg
//If a nonvolatile setting is changed it is saved to that file immediately
#include "q_shared.h"
#include "qcommon_io.h"
#include "qcommon_mem.h"
#include "filesystem.h"
#include "cmd.h"
#include "server.h"
#include "hl2rcon.h"

#include <string.h>

#define MAX_NVCONFIG_SIZE 2048*128

#define NV_ProcessBegin NV_LoadConfig
#define NV_ProcessEnd NV_WriteConfig

/*
================
NV_ParseConfigLine
================
*/

qboolean NV_ParseConfigLine(char* line, int linenumber){

/*    char username[32];
    char password[65];
    char salt[129];
    char tmp[1024];
*/
    if(!Q_stricmp(Info_ValueForKey(line, "type") , "cmdMinPower")){

        if(!Cmd_InfoSetPower( line )){
            Com_DPrintf("Warning at line: %d\n", linenumber);
            return qtrue; //Don't rise errors here! This can happen for commands we add at a later stage
        }
        return qtrue;

    }else if(!Q_stricmp(Info_ValueForKey(line, "type") , "rconAdmin")){
/*
        power = atoi(Info_ValueForKey(line, "power"));
        Q_strncpyz(password, Info_ValueForKey(line, "password") , sizeof(password));
        Q_strncpyz(salt, Info_ValueForKey(line, "salt") , sizeof(salt));
        Q_strncpyz(username, Info_ValueForKey(line, "username") , sizeof(username));

        if(!HL2Rcon_AddSourceRconAdminToList(username, password, salt, power)){
            Com_Printf("Error: duplicated username or bad power or too many admins (line: %d)\n", linenumber);
            return qfalse;
        }*/
        return qtrue;

    }else if(!Q_stricmp(Info_ValueForKey(line, "type") , "admin")){

        if(!SV_RemoteCmdInfoAddAdmin( line ))
        {
            Com_Printf("Error at line: %d\n", linenumber);
            return qfalse;
        }
        return qtrue;

    }else{
        Com_Printf("Error: unknown type (line: %d)\n", linenumber);
        return qfalse;
    }
}


/*
================
NV_LoadConfig
================
*/

void NV_LoadConfig(){

    int read, i;
    int error = 0;
    char buf[256];
    *buf = 0;
    fileHandle_t file;

    SV_RemoteCmdClearAdminList();
    HL2Rcon_ClearSourceRconAdminList();

    FS_SV_FOpenFileRead("nvconfig.dat", &file);
    if(!file){
        Com_DPrintf("Couldn't open nvconfig.dat for reading\n");
        return;
    }
    Com_Printf( "loading nvconfig.dat\n");

    i = 0;

    while(qtrue){
        read = FS_ReadLine(buf,sizeof(buf),file);
        if(read == 0){
            FS_FCloseFile(file);
            Com_Printf("Loaded nvconfig.dat %i errors\n", error);
            return;
        }
        if(read == -1){
            Com_Printf("Can not read from nvconfig.dat\n");
            FS_FCloseFile(file);
            return;
        }
        i++;//linecouter

        if(!*buf || *buf == '/' || *buf == '\n'){
            continue;
        }
        if(!NV_ParseConfigLine(buf, i)){
            error++;
        }
    }
}

/*
================
NV_WriteConfig
================
*/

void NV_WriteConfig(){

    char* buffer;

    buffer = Hunk_AllocateTempMemory(MAX_NVCONFIG_SIZE);
    if(!buffer){
        Com_Printf( "Error Updating NVConfig: Hunk_Alloc failed\n" );
        return;
    }
    Com_Memset(buffer,0,MAX_NVCONFIG_SIZE);
    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"//Autogenerated non volatile config settings\n");

    Cmd_WritePowerConfig( buffer, MAX_NVCONFIG_SIZE );
    SV_RemoteCmdWriteAdminConfig( buffer, MAX_NVCONFIG_SIZE );

/*
    rconLogin_t *rconadmin;
    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"\n//RconAdmins\n");

    for ( rconadmin = sourceRcon.rconUsers, i = 0; i < MAX_RCONLOGINS ; rconadmin++, i++ ){
        *infostring = 0;
	if(!*rconadmin->username)
		continue;
        Info_SetValueForKey(infostring, "type", "rconAdmin");
        Info_SetValueForKey(infostring, "power", va("%i", rconadmin->power));
        Info_SetValueForKey(infostring, "password", rconadmin->sha256);
        Info_SetValueForKey(infostring, "salt", rconadmin->salt);
        Info_SetValueForKey(infostring, "username", rconadmin->username);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, infostring);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, "\\\n");
    }
*/

    FS_SV_WriteFile("nvconfig.dat", buffer, strlen(buffer));
    Hunk_FreeTempMemory( buffer );
    Com_DPrintf("NV-Config Updated\n");
}
